apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: wordpress
type: Opaque
stringData:
  db-host: "proxysql-mysql-svc.database.svc.cluster.local"
  db-port: "3306"
  db-name: "wordpress_db"
  db-user: "wordpress_user"
  db-password: "WordPress_Pass_789"
