apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-backup
  labels:
    pv: pv-backup
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 172.100.100.20
    path: "/nfs/backup"
