apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-database-1
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      pv: pv-database-1
