apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backup
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      pv: pv-backup
