apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secret
  namespace: fastapi
type: Opaque
stringData:
  db-host: "proxysql-mysql-svc.database.svc.cluster.local"
  db-port: "3306"
  db-name: "fastapi_db"
  db-user: "fastapi_user"
  db-password: "FastAPI_Pass_000"
  redis-host: "redis-svc.fastapi.svc.cluster.local"
  redis-port: "6379"
  naver-api-key: "Your_Naver_API_Key"
  naver-api-secret: "Your_Naver_API_Secret"
